"""Spike sorting pipeline for use with HPC.

Pipeline parameters live in spikeshpc.config.DEFAULT_PIPELINE and can be
overridden per-run either by passing kwargs to run_pipeline() directly (e.g.
from a notebook) or, from the CLI, via a --pipeline_config JSON file that is
merged with the defaults.
"""

from .config import DEFAULT_PIPELINE, deep_merge
from .decoder import (
    Decoded,
    DecoderData,
    DecoderRun,
    EncodingModel,
    ShuffleTest,
    TransferRun,
    apply_decoder,
    bins_in_interval_mask,
    decode,
    fit_encoding_model,
    metrics_by_group,
    plot_decoded,
    plot_encoding_model,
    plot_error,
    plot_metrics_by_group,
    plot_shuffle,
    plot_transfer_summary,
    prepare_decoder_data,
    reference_decode,
    restrict_data,
    restrict_model,
    run_decoder,
    shuffle_test,
    split_train_test,
    state_interval_mask,
)
from .decoder_widget import DecodedWidget, show_decoded
from .drift import drift_at_junction, plot_drift
from .editor import StateEditor, show_state_editor
from .io import (
    StateScoring,
    detect_phys_type,
    load_concatenated,
    load_states,
    open_stream,
    probe_start_time,
    read_openephys_synced,
    read_recording,
    sync_clock_problem,
)
from .matching import (
    estimate_rotation,
    plot_tracked_tuning,
    putative_matches,
    recording_colors,
    select_partners,
    tuning_similarity,
)
from .pipeline import run_pipeline
from .raster import UnitRaster, unit_raster
from .ring import (
    RingModel,
    RingRun,
    compare_rings,
    decode_ring,
    fit_ring,
    pair_decodes,
    plot_correlograms,
    plot_ring,
    plot_ring_comparison,
    plot_ring_vs_tuning,
    ring_vs_tuning,
    run_ring,
)
from .shutter import derive_shutter_times
from .split import SessionSplit, save_splits, split_run
from .states import (
    attach_movement,
    behavior_interval_mask,
    frames_in_states,
    interval_mask_to_spans,
    rescore_movement,
    score_recording,
    score_session,
    seconds_since,
    slice_recording_to_states,
    times_in_states,
)
from .traces import get_traces, plot_traces, time_range_to_frames
from .tracking import (
    git_commit,
    recording_paths,
    run_unitmatch,
    waveform_status,
)
from .turns import (
    Turns,
    clockwise_sign,
    find_turns,
    plot_turn_summary,
    plot_turn_sweep,
    plot_turn_trace,
)
from .turns_widget import TurnWidget, show_turns
from .widgets import show_state_epochs

__all__ = [
    "DEFAULT_PIPELINE",
    "Decoded",
    "DecodedWidget",
    "DecoderData",
    "DecoderRun",
    "EncodingModel",
    "RingModel",
    "RingRun",
    "SessionSplit",
    "ShuffleTest",
    "StateEditor",
    "StateScoring",
    "TransferRun",
    "TurnWidget",
    "Turns",
    "UnitRaster",
    "apply_decoder",
    "attach_movement",
    "behavior_interval_mask",
    "bins_in_interval_mask",
    "clockwise_sign",
    "compare_rings",
    "decode",
    "decode_ring",
    "deep_merge",
    "derive_shutter_times",
    "detect_phys_type",
    "drift_at_junction",
    "estimate_rotation",
    "find_turns",
    "fit_encoding_model",
    "fit_ring",
    "get_traces",
    "git_commit",
    "frames_in_states",
    "interval_mask_to_spans",
    "load_concatenated",
    "load_states",
    "metrics_by_group",
    "open_stream",
    "pair_decodes",
    "plot_correlograms",
    "plot_decoded",
    "plot_drift",
    "plot_encoding_model",
    "plot_error",
    "plot_metrics_by_group",
    "plot_ring",
    "plot_ring_comparison",
    "plot_ring_vs_tuning",
    "plot_shuffle",
    "plot_tracked_tuning",
    "plot_traces",
    "plot_transfer_summary",
    "plot_turn_summary",
    "plot_turn_sweep",
    "plot_turn_trace",
    "prepare_decoder_data",
    "probe_start_time",
    "putative_matches",
    "read_openephys_synced",
    "read_recording",
    "recording_colors",
    "recording_paths",
    "reference_decode",
    "rescore_movement",
    "restrict_data",
    "restrict_model",
    "ring_vs_tuning",
    "run_decoder",
    "run_pipeline",
    "run_unitmatch",
    "run_ring",
    "save_splits",
    "score_recording",
    "score_session",
    "seconds_since",
    "select_partners",
    "show_decoded",
    "show_state_editor",
    "show_state_epochs",
    "show_turns",
    "shuffle_test",
    "slice_recording_to_states",
    "split_run",
    "split_train_test",
    "state_interval_mask",
    "sync_clock_problem",
    "time_range_to_frames",
    "times_in_states",
    "tuning_similarity",
    "unit_raster",
    "waveform_status",
]
